---
# Source: ingress/charts/controller/templates/admission-webhook.yaml
apiVersion: v1
kind: Secret
metadata:
  name: kong-ingress-controller-validation-webhook-ca-keypair
  namespace:  kong
  labels:
    app.kubernetes.io/name: controller
    helm.sh/chart: controller-2.46.0
    app.kubernetes.io/instance: "kong-ingress"
    app.kubernetes.io/managed-by: "Helm"
    
    app.kubernetes.io/version: "3.8"
type: kubernetes.io/tls
data:
    tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJekNDQWd1Z0F3SUJBZ0lRVU0zbkZCZ3FzeWRQYlc5RjkyUkxyakFOQmdrcWhraUc5dzBCQVFzRkFEQWMKTVJvd0dBWURWUVFERXhGcmIyNW5MV0ZrYldsemMybHZiaTFqWVRBZUZ3MHlOVEF4TURJeE1ESXpOVGhhRncwegpOREV5TXpFeE1ESXpOVGhhTUJ3eEdqQVlCZ05WQkFNVEVXdHZibWN0WVdSdGFYTnphVzl1TFdOaE1JSUJJakFOCkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXdON3ptY21YcTBiNkZaQWM4R2ZlVVFJWUk4YTMKdmF6bjdGeWxPRDBSTDFuUWNqdjM1bXA1QWd6d3dFTFZML0YrZ1k2U01QVFJlWWhSTmhzYXlsVkVlR1lDeDR2SgpCcytiQTR4OW9rU2c3Wk4rcmtqSzl0UG96dXdDS1E2dGVoSmZWcUVFdzlaaFBOMlFTMS94Zm55SHFqUzRVUE1nCjJTcFpWTjMrU3BBUTQyNzZ3MWJ0d1Nnd012Ui9uSnpaUWJxZUZicEhTSjRHdm03VG9rdzBWWmsyVEpMME1EcUgKMmgrMlF1YU9OQkdkQWh0bVJZZDVwU1VYRnhxVGVHRTlZZnNPQVhXeW9xSGF1MzJjSkxzZWtuVVZCYWU1S1dWcApXSTNUNFFpT2ZzZGNuWTZtUFVmeVlSY1dyNTBod3RyVUxlcHFLd1lzdFFsQWdSb0Y5M040K2duN3pRSURBUUFCCm8yRXdYekFPQmdOVkhROEJBZjhFQkFNQ0FxUXdIUVlEVlIwbEJCWXdGQVlJS3dZQkJRVUhBd0VHQ0NzR0FRVUYKQndNQ01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZOOEt0MTJiVXhtcEw2RkN0em9kTlVQWAo2SlIrTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFDYTV4eEI0UnFWUVkxaCtvbEtCMG5BRHhONDd6bjhVY3BIClNzdkdvYjZaYmtjOHY5M0ZUcjhXNit5Tk9GSGQ4Wk5za2JMenVJblZmS0pRUjJSVHZMTVdCajlOUllHd1ZKRHIKYVprbE8yL2k4NkhBa2wyT1hKUlJzTEhNWTA2VTdxenBJTWhDWHpKdk5WekdoNFhGd3k0T2g5Q2J4dTNMTWN3Vwp0Wk5lVXIyZEpYUEF5TVFrVmVYTzd1WkFJNFpCbnNxQ3N0RlNnNEUvWGlDbEFUemNpbW1hSjhLK0Y4TUc0ay9aCjcxZVJQS25XRytnUHdhZ1ZSRnlBc2NmM3E4V1dvOHIzRENlM20rcjZiSGlhY0JFZVFlNnUrRWZoQjROZ3kvUXcKQ1VQTzIzUU1rc3gvY0dJS3U4U1VDU2VXbGJGWjYycVpYeWlXWERIRDB5TTNOdjl1NXQ2YgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBd043em1jbVhxMGI2RlpBYzhHZmVVUUlZSThhM3Zhem43RnlsT0QwUkwxblFjanYzCjVtcDVBZ3p3d0VMVkwvRitnWTZTTVBUUmVZaFJOaHNheWxWRWVHWUN4NHZKQnMrYkE0eDlva1NnN1pOK3JraksKOXRQb3p1d0NLUTZ0ZWhKZlZxRUV3OVpoUE4yUVMxL3hmbnlIcWpTNFVQTWcyU3BaVk4zK1NwQVE0Mjc2dzFidAp3U2d3TXZSL25KelpRYnFlRmJwSFNKNEd2bTdUb2t3MFZaazJUSkwwTURxSDJoKzJRdWFPTkJHZEFodG1SWWQ1CnBTVVhGeHFUZUdFOVlmc09BWFd5b3FIYXUzMmNKTHNla25VVkJhZTVLV1ZwV0kzVDRRaU9mc2Rjblk2bVBVZnkKWVJjV3I1MGh3dHJVTGVwcUt3WXN0UWxBZ1JvRjkzTjQrZ243elFJREFRQUJBb0lCQUFQekRNM3pZTld6Q0YvMApxWU1LdlhTdk5FdFhRRi96OEhQWW1kR0MvcDBYbTdzYkcwSnVuN2U1Q0IwSHdWSFFBaVVwQkRsWWFnbXhEdWlxCnVXdTNQMFd2NFJLdy9CYlZuWGovSVh0M0tFeDFIcnoyNUtFVlNja2k4QkJqS280N1hoUnFDNnp1OE9MTUxxNDgKY3JlQ1dVelU4NGxFMFVGaEtwOGdSSnJHUkhKRHhGYzZUZUJyNmZ5T3hGRG1wcEdqeVh0NGF2UTJLMzhuS1FpTQo2YTU4Titkd0w1Q0VSZWRTdC9LbFM1N3NGdGt6NjRJN0N3Y0NMWHgwQ0lxajNmWnVuUU5veXpPeUVyZDNHQ3pKCkdlbzY5Qm50ZjMrV0tPMXdIakJIWUV4a2RrZU1IcmJvT09wRzI2VW9OUlltdVBsZWdoN1NWQUtVR2grM05SMmIKTEZIWFZra0NnWUVBeEZUWEdsbzZrZGFZL0NOdVBuZjIvRS80eHBtRElLemlTZllGV2lKZ29EaUhkelZ6VlJhWgpHNjFSN3p5blE0RzdNSXhhNUp1ZW5UenVFZlVPdnNEd3JLSTltalpWVnRjb0ZWemlYOVpXY2JyQ0dacmVCVHlwCk5FNmNPUWo1U2xja1RsQXpDQzBYMmRyYjVpNlRSY2lHaERwdVhDL2QwWFdaM1Z2OHZabU1sYU1DZ1lFQSszemYKd2hoZi95MUphbHM5TkJxVUhBQWx3dkxOSDg2b1dtdHR1UjltclFqMnNlQjc5V3FEVHlvaTRJdmh6eVVMd2hnUgpRUmZMRGlTcGRHbXV0U0VmRnBiMU5uaERxVjUwNFRsTDFKdm9CR2wrdU9sbFZuTnhlYm5OZ3VlOEF3TXhFTVIyClBJUW8xcFN3QkpKb2lLZmZtNnZWZGs3NDhHbyt3cFlSUXdFczM4OENnWUVBbzNXUGNaMVZ6ajVCT1F1MnFjUHYKbXJwcWdjOGw0WHFQSE16OFA4TUhkOTRZeXlOeFZwSnQveUVhYW5peE9mODAvb0tjMm1ER2VsdFVTeGNnbzZpMwp1TU9MVG0yV042c0M4R1paQXpuTTF2dUt4dzZ0Y3ViQ2FZNVpleE1CbXVkYWp1a3UwOHZYWThaWDl4a24vSjJyCmdVTzB4b1FEeG5TSEdrbVA3N3Q3MU1rQ2dZQjRhbTVwYldwcHNMRjZiMzE2dVU4NXFRaHJzLzVyd0hQejk0UnUKSTQ3eVExeDhCMVRUU2REZDB2c29NVkpKOFI4VUxKbjJaUUloSDRUVDdOWnVmQkY2cTRWMk0xZVNmVnZSaTdHMwpkMzg4dlphankzMXVTNUNHREdWT3pNN0ZVbjNuM1dvUHgrZ1Y5dFBoSElsWkJhaVh6VXRFZnNQTHVkT2JNR2ZMCmdZQ1BHUUtCZ0g5WmJORTk3RjBXOGlpS01tWTJlUVRvV3JtTm1ncDBOampvWUxRY1c3UWt0MHlFaFdlc20rT1gKOEtmYTN2WEhMY1EwZ3p5cTVxZWNtQkVlRFlCZjRPclJ0UDFtVHF5cHdKMUJtTExCVWEzMHg4YTZWaXJOMDE2Vwo4SXAzNkt1V0YvREtYOUQwOW1xUUhkbWFOQk1tWUNDSkJGWlQyenNvZGdTcE9taWliS3VJCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
---
# Source: ingress/charts/controller/templates/admission-webhook.yaml
apiVersion: v1
kind: Secret
metadata:
  name: kong-ingress-controller-validation-webhook-keypair
  namespace:  kong
  labels:
    app.kubernetes.io/name: controller
    helm.sh/chart: controller-2.46.0
    app.kubernetes.io/instance: "kong-ingress"
    app.kubernetes.io/managed-by: "Helm"
    
    app.kubernetes.io/version: "3.8"
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURoakNDQW02Z0F3SUJBZ0lRRHJHb1BjK05SRVkxV1dlYzlzU09tekFOQmdrcWhraUc5dzBCQVFzRkFEQWMKTVJvd0dBWURWUVFERXhGcmIyNW5MV0ZrYldsemMybHZiaTFqWVRBZUZ3MHlOVEF4TURJeE1ESXpOVGhhRncwegpOREV5TXpFeE1ESXpOVGhhTUQ0eFBEQTZCZ05WQkFNVE0ydHZibWN0YVc1bmNtVnpjeTFqYjI1MGNtOXNiR1Z5CkxYWmhiR2xrWVhScGIyNHRkMlZpYUc5dmF5NXJiMjVuTG5OMll6Q0NBU0l3RFFZSktvWklodmNOQVFFQkJRQUQKZ2dFUEFEQ0NBUW9DZ2dFQkFPaTdaTm5sNlo1b2NqNzZpOUxncmlDTHVWZ2MxQmx5Tkl6YmFiYmFjSUJIMUFvegpJMGV4WllqNnk3emZpZWE3cEVLTVB0aVJMQkVqMERrSGpHSmdaWEo1QmpGQng3S1pOMnBnb0JuNVlSVkdKaCtaCkxPajhDbjlES0NTa3BkaU1lU2lOa05vditmMmhVVld1OE1nTTdBb0VyTnQ5QWU0QTdjS1ljWVNsN3U0Mmlac1YKUFdqL1Q3Z21FTFA1dE13bXZjcTBxbC9halZGWnNuTkJDdktvejAxQTlxekU4MWdUR20rY3k1WStNU0kwVW5iWQpMTkNIbm9KMEYydmtxV1hjdGtNK0t0cEN6VmVXZmFGd1dadWRJM3U2dm5waEQ5KzFsQ2QrMnNQTDh2QTIvVWJvCjM0alp1bFhXeVMvNmlqdTR2MDJUc0N2NERURnA2VkRGclpQMTV5VUNBd0VBQWFPQm9UQ0JuakFPQmdOVkhROEIKQWY4RUJBTUNCYUF3SFFZRFZSMGxCQll3RkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ01Bd0dBMVVkRXdFQgovd1FDTUFBd0h3WURWUjBqQkJnd0ZvQVUzd3EzWFp0VEdha3ZvVUszT2gwMVE5Zm9sSDR3UGdZRFZSMFJCRGN3Ck5ZSXphMjl1WnkxcGJtZHlaWE56TFdOdmJuUnliMnhzWlhJdGRtRnNhV1JoZEdsdmJpMTNaV0pvYjI5ckxtdHYKYm1jdWMzWmpNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUNWejFEbDB0b1FUUythN1J2YlVTQjE3SDc5a1lWcwprQ2ptb1o4MVJZZHZCRSs3WW5BaHBtUDY3N0JUY3lWeHlmVW5aVHF1aW1ZSlVIeE95SUxnNUpXUlpLRzg3NERsCkh3YXBjSFdKbkdwcDRSZXZnRGYzQmZTQU5jWFRJbEpxM0xLd1NhOW1CTGlRL1pzaU5LK2tmb2VTbU5mV3o1c24KTTQ2U3QyR1pPckxxK1BGeUVaaXRNTGdPZVJGbFVLcjlrRnBIdFpMa1oxaGEyU3VUU2JuK0VqQm5BVVlPd0VIMwpHb0o3Y2x4dGVybmtoNFZLNUMvaHFYY3NDbnZFRnFmUVBsNDNBTGJNS3ZpR0xjUEZHZUduU3NlYWxmSDU2MUthCm51b2RXS25nblFKSjlURlBTTWRpb1JHcFVUNkRaTm9XMUNMaWtuSitpUFNlQTRBazhOQnlNaVF3Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBNkx0azJlWHBubWh5UHZxTDB1Q3VJSXU1V0J6VUdYSTBqTnRwdHRwd2dFZlVDak1qClI3RmxpUHJMdk4rSjVydWtRb3crMkpFc0VTUFFPUWVNWW1CbGNua0dNVUhIc3BrM2FtQ2dHZmxoRlVZbUg1a3MKNlB3S2YwTW9KS1NsMkl4NUtJMlEyaS81L2FGUlZhN3d5QXpzQ2dTczIzMEI3Z0R0d3BoeGhLWHU3amFKbXhVOQphUDlQdUNZUXMvbTB6Q2E5eXJTcVg5cU5VVm15YzBFSzhxalBUVUQyck1UeldCTWFiNXpMbGo0eElqUlNkdGdzCjBJZWVnblFYYStTcFpkeTJRejRxMmtMTlY1WjlvWEJabTUwamU3cStlbUVQMzdXVUozN2F3OHZ5OERiOVJ1amYKaU5tNlZkYkpML3FLTzdpL1RaT3dLL2dOTVducFVNV3RrL1huSlFJREFRQUJBb0lCQVFEQ3lwNEZ0dWFMZkhZcQorajl2dURobDZ5eXRjQ3VpUkxGeE4vQkthSmlDOWh1bWtkaTBsK2tZOW5qeVU5TXpPTmlxRG9KSGQzSi93ZzcwCnZMbW1XWEp2bHBZMVFnNW9FTStPRE9QVCthTmxUL3AydGhrZHhGN3cxMy9RODdJUUJyc2QweWRyUjM2ZzU1V1EKOXNSM1hFRnZ2U3dFNWFObzFvUXFQTGUrdzdld3pvSlNsZDBsRkprWktpaFVhMTY0MHNYaUZqMFpSZEwwSG1WRgpFUHQwaUV0NnRUQi83d256Mmh5Q1g0K1lCNDZnZVpyWHZTZ1M3WGNkc3Nkblhhc3VaekthYnJjSFlYTGFaME9OCnV5UkJYWU00QnFCQ0tPcUFLZFNUQjJRWmN2T0Qxdm9nSThUMXZDQkpTM2c0ZHZPc1NCalgwaU8xWFN3YkdzREoKMGptQlFBbWRBb0dCQVBRRzRFRjBER0NzQ2VCNjhPVytxT2hSRHpoZkFlWm03VmJJbEhNeVFNUjVOWDJLVEVTRQplbVd5M1R3blVoNnMvM2V0dGRaWmRIMFlXb0FGK3hiV2lBL0RmNjVtd3ZoTk15bkRLZTFzSXhIRE5UWUNtK2pGCkY2aFdteTNxS0tUNXZabm9ZWHczbUl1SHVMdjExaDN6SjkyQ2FTOXBmVWZLNERjelBGNzBieUFqQW9HQkFQUW0KcGRmajd5aEdnSzVWRU9DZVUxUDY1T1d5UWp1aGE0MjBUa1VYYzhCMWx5OGhFR3JtQ2s4VCtYdVpzZGF4SEhvdwoxd2dYYS9HV0NTaUplK3hKcEJaeTBkTDQrN0xOMUFXMjRkZis4ME9xS3FWdXIvS0l4OE1mK045SVh6MnIwOXZGCjdDaGpwcy9PVm44eUx5Z1BWS2lBYmEvWSthUk9MNTl2YnVLMi9Dd1hBb0dBSUNGTG83S1k4cDJVUzFkRW9xdGcKNS8zTVNEclNNRGo3SlFNUjhMejhKQ0psZFpzaEFhQ0QwU0lrMlFmQVcwT2grMnNHMXlzK0dENTlvLytsbU5NMApaUWJ6cDgzbCsvV0dPQWgzVzhoeU1hT0hQUTVJNHZRWWNsUzg1K1c5NWtMdndQVUU2T3NWRGNJWUE3K1JxcTNhCllPTUw0RzgrVEphY3dRZmcrZ3VyR2dzQ2dZQU1tSFhUMW5GL0hXd0VFbVZsZ1NXQlhwOHlibWpXVkxTTXdmR0wKeFBMMnlkbzcxelBXbi9tR0xOeWhFTVBJOUtnb2NaNldUMGNGVnAwd1Z5OXFlRDRiM2w2T3lNT0xiT3owUW9RUwpOWmZ0Tkxrd2dhNVlEOUJtYzU3T1BoaVR3T3FVR3ZqYytJOGhoMTZVLzB6SmYwajV6RzVjTlJCajlwaWtYQVpYCmNlTStqd0tCZ0M2RHk3U1lQYWNHOHlrK2VsNThENjhjekZoK1QzK2E3QXQyTmdyVXMrVHp1ZXI0NzZSWjdtYmEKMEMreFFwU2hGZjZKdVNXaytTZFlZVHRQNlBuL0hERWR1OWsxODBCZ2x0eWc3ZmprRnBPSGljVGYrSlc1L0R4SQpEWnY0UmtlZWdoaDZFV1hyQWZHRlNiQVpNQnRGcHFnVzBQL3VmYVdOSGhsb053enM0UzdzCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
---
# Source: ingress/charts/controller/templates/admission-webhook.yaml
apiVersion: v1
kind: Service
metadata:
  name: kong-ingress-controller-validation-webhook
  namespace: kong
  labels:
    app.kubernetes.io/name: controller
    helm.sh/chart: controller-2.46.0
    app.kubernetes.io/instance: "kong-ingress"
    app.kubernetes.io/managed-by: "Helm"
    
    app.kubernetes.io/version: "3.8"
spec:
  ports:
  - name: webhook
    port: 443
    protocol: TCP
    targetPort: webhook
  selector:
    app.kubernetes.io/name: controller
    helm.sh/chart: controller-2.46.0
    app.kubernetes.io/instance: "kong-ingress"
    app.kubernetes.io/managed-by: "Helm"
    
    app.kubernetes.io/version: "3.8"
    app.kubernetes.io/component: app
---
# Source: ingress/charts/controller/templates/admission-webhook.yaml
kind: ValidatingWebhookConfiguration
apiVersion: admissionregistration.k8s.io/v1
metadata:
  name: kong-ingress-controller-validations
  namespace: kong
  labels:
    app.kubernetes.io/name: controller
    helm.sh/chart: controller-2.46.0
    app.kubernetes.io/instance: "kong-ingress"
    app.kubernetes.io/managed-by: "Helm"
    
    app.kubernetes.io/version: "3.8"
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJekNDQWd1Z0F3SUJBZ0lRVU0zbkZCZ3FzeWRQYlc5RjkyUkxyakFOQmdrcWhraUc5dzBCQVFzRkFEQWMKTVJvd0dBWURWUVFERXhGcmIyNW5MV0ZrYldsemMybHZiaTFqWVRBZUZ3MHlOVEF4TURJeE1ESXpOVGhhRncwegpOREV5TXpFeE1ESXpOVGhhTUJ3eEdqQVlCZ05WQkFNVEVXdHZibWN0WVdSdGFYTnphVzl1TFdOaE1JSUJJakFOCkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXdON3ptY21YcTBiNkZaQWM4R2ZlVVFJWUk4YTMKdmF6bjdGeWxPRDBSTDFuUWNqdjM1bXA1QWd6d3dFTFZML0YrZ1k2U01QVFJlWWhSTmhzYXlsVkVlR1lDeDR2SgpCcytiQTR4OW9rU2c3Wk4rcmtqSzl0UG96dXdDS1E2dGVoSmZWcUVFdzlaaFBOMlFTMS94Zm55SHFqUzRVUE1nCjJTcFpWTjMrU3BBUTQyNzZ3MWJ0d1Nnd012Ui9uSnpaUWJxZUZicEhTSjRHdm03VG9rdzBWWmsyVEpMME1EcUgKMmgrMlF1YU9OQkdkQWh0bVJZZDVwU1VYRnhxVGVHRTlZZnNPQVhXeW9xSGF1MzJjSkxzZWtuVVZCYWU1S1dWcApXSTNUNFFpT2ZzZGNuWTZtUFVmeVlSY1dyNTBod3RyVUxlcHFLd1lzdFFsQWdSb0Y5M040K2duN3pRSURBUUFCCm8yRXdYekFPQmdOVkhROEJBZjhFQkFNQ0FxUXdIUVlEVlIwbEJCWXdGQVlJS3dZQkJRVUhBd0VHQ0NzR0FRVUYKQndNQ01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZOOEt0MTJiVXhtcEw2RkN0em9kTlVQWAo2SlIrTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFDYTV4eEI0UnFWUVkxaCtvbEtCMG5BRHhONDd6bjhVY3BIClNzdkdvYjZaYmtjOHY5M0ZUcjhXNit5Tk9GSGQ4Wk5za2JMenVJblZmS0pRUjJSVHZMTVdCajlOUllHd1ZKRHIKYVprbE8yL2k4NkhBa2wyT1hKUlJzTEhNWTA2VTdxenBJTWhDWHpKdk5WekdoNFhGd3k0T2g5Q2J4dTNMTWN3Vwp0Wk5lVXIyZEpYUEF5TVFrVmVYTzd1WkFJNFpCbnNxQ3N0RlNnNEUvWGlDbEFUemNpbW1hSjhLK0Y4TUc0ay9aCjcxZVJQS25XRytnUHdhZ1ZSRnlBc2NmM3E4V1dvOHIzRENlM20rcjZiSGlhY0JFZVFlNnUrRWZoQjROZ3kvUXcKQ1VQTzIzUU1rc3gvY0dJS3U4U1VDU2VXbGJGWjYycVpYeWlXWERIRDB5TTNOdjl1NXQ2YgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    service:
      name: kong-ingress-controller-validation-webhook
      namespace: kong
  failurePolicy: Ignore
  matchPolicy: Equivalent
  name: secrets.credentials.validation.ingress-controller.konghq.com
  objectSelector:
    matchExpressions:
    - key: "konghq.com/credential"
      operator: "Exists"
    - key: "konghq.com/credential"
      operator: "NotIn"
      values:
      - "konnect"
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - secrets
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJekNDQWd1Z0F3SUJBZ0lRVU0zbkZCZ3FzeWRQYlc5RjkyUkxyakFOQmdrcWhraUc5dzBCQVFzRkFEQWMKTVJvd0dBWURWUVFERXhGcmIyNW5MV0ZrYldsemMybHZiaTFqWVRBZUZ3MHlOVEF4TURJeE1ESXpOVGhhRncwegpOREV5TXpFeE1ESXpOVGhhTUJ3eEdqQVlCZ05WQkFNVEVXdHZibWN0WVdSdGFYTnphVzl1TFdOaE1JSUJJakFOCkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXdON3ptY21YcTBiNkZaQWM4R2ZlVVFJWUk4YTMKdmF6bjdGeWxPRDBSTDFuUWNqdjM1bXA1QWd6d3dFTFZML0YrZ1k2U01QVFJlWWhSTmhzYXlsVkVlR1lDeDR2SgpCcytiQTR4OW9rU2c3Wk4rcmtqSzl0UG96dXdDS1E2dGVoSmZWcUVFdzlaaFBOMlFTMS94Zm55SHFqUzRVUE1nCjJTcFpWTjMrU3BBUTQyNzZ3MWJ0d1Nnd012Ui9uSnpaUWJxZUZicEhTSjRHdm03VG9rdzBWWmsyVEpMME1EcUgKMmgrMlF1YU9OQkdkQWh0bVJZZDVwU1VYRnhxVGVHRTlZZnNPQVhXeW9xSGF1MzJjSkxzZWtuVVZCYWU1S1dWcApXSTNUNFFpT2ZzZGNuWTZtUFVmeVlSY1dyNTBod3RyVUxlcHFLd1lzdFFsQWdSb0Y5M040K2duN3pRSURBUUFCCm8yRXdYekFPQmdOVkhROEJBZjhFQkFNQ0FxUXdIUVlEVlIwbEJCWXdGQVlJS3dZQkJRVUhBd0VHQ0NzR0FRVUYKQndNQ01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZOOEt0MTJiVXhtcEw2RkN0em9kTlVQWAo2SlIrTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFDYTV4eEI0UnFWUVkxaCtvbEtCMG5BRHhONDd6bjhVY3BIClNzdkdvYjZaYmtjOHY5M0ZUcjhXNit5Tk9GSGQ4Wk5za2JMenVJblZmS0pRUjJSVHZMTVdCajlOUllHd1ZKRHIKYVprbE8yL2k4NkhBa2wyT1hKUlJzTEhNWTA2VTdxenBJTWhDWHpKdk5WekdoNFhGd3k0T2g5Q2J4dTNMTWN3Vwp0Wk5lVXIyZEpYUEF5TVFrVmVYTzd1WkFJNFpCbnNxQ3N0RlNnNEUvWGlDbEFUemNpbW1hSjhLK0Y4TUc0ay9aCjcxZVJQS25XRytnUHdhZ1ZSRnlBc2NmM3E4V1dvOHIzRENlM20rcjZiSGlhY0JFZVFlNnUrRWZoQjROZ3kvUXcKQ1VQTzIzUU1rc3gvY0dJS3U4U1VDU2VXbGJGWjYycVpYeWlXWERIRDB5TTNOdjl1NXQ2YgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    service:
      name: kong-ingress-controller-validation-webhook
      namespace: kong
  failurePolicy: Ignore
  matchPolicy: Equivalent
  name: secrets.plugins.validation.ingress-controller.konghq.com
  objectSelector:
    matchExpressions:
    - key: owner
      operator: NotIn
      values:
      - helm
    - key: "konghq.com/credential"
      operator: "NotIn"
      values:
      - "konnect"
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - secrets
  sideEffects: None
- name: validations.kong.konghq.com
  matchPolicy: Equivalent
  objectSelector:
    matchExpressions:
    - key: owner
      operator: NotIn
      values:
      - helm
  failurePolicy: Ignore
  sideEffects: None
  admissionReviewVersions: ["v1beta1"]
  rules:
  - apiGroups:
    - configuration.konghq.com
    apiVersions:
    - '*'
    operations:
    - CREATE
    - UPDATE
    resources:
    - kongconsumers
    - kongplugins
    - kongclusterplugins
    - kongingresses
  - apiGroups:
    - ''
    apiVersions:
    - 'v1'
    operations:
    - CREATE
    - UPDATE
    resources:
    - services
  - apiGroups:
    - networking.k8s.io
    apiVersions:
      - 'v1'
    operations:
    - CREATE
    - UPDATE
    resources:
    - ingresses
  - apiGroups:
    - gateway.networking.k8s.io
    apiVersions:
    - 'v1alpha2'
    - 'v1beta1'
    - 'v1'
    operations:
    - CREATE
    - UPDATE
    resources:
    - gateways
    - httproutes
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJekNDQWd1Z0F3SUJBZ0lRVU0zbkZCZ3FzeWRQYlc5RjkyUkxyakFOQmdrcWhraUc5dzBCQVFzRkFEQWMKTVJvd0dBWURWUVFERXhGcmIyNW5MV0ZrYldsemMybHZiaTFqWVRBZUZ3MHlOVEF4TURJeE1ESXpOVGhhRncwegpOREV5TXpFeE1ESXpOVGhhTUJ3eEdqQVlCZ05WQkFNVEVXdHZibWN0WVdSdGFYTnphVzl1TFdOaE1JSUJJakFOCkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXdON3ptY21YcTBiNkZaQWM4R2ZlVVFJWUk4YTMKdmF6bjdGeWxPRDBSTDFuUWNqdjM1bXA1QWd6d3dFTFZML0YrZ1k2U01QVFJlWWhSTmhzYXlsVkVlR1lDeDR2SgpCcytiQTR4OW9rU2c3Wk4rcmtqSzl0UG96dXdDS1E2dGVoSmZWcUVFdzlaaFBOMlFTMS94Zm55SHFqUzRVUE1nCjJTcFpWTjMrU3BBUTQyNzZ3MWJ0d1Nnd012Ui9uSnpaUWJxZUZicEhTSjRHdm03VG9rdzBWWmsyVEpMME1EcUgKMmgrMlF1YU9OQkdkQWh0bVJZZDVwU1VYRnhxVGVHRTlZZnNPQVhXeW9xSGF1MzJjSkxzZWtuVVZCYWU1S1dWcApXSTNUNFFpT2ZzZGNuWTZtUFVmeVlSY1dyNTBod3RyVUxlcHFLd1lzdFFsQWdSb0Y5M040K2duN3pRSURBUUFCCm8yRXdYekFPQmdOVkhROEJBZjhFQkFNQ0FxUXdIUVlEVlIwbEJCWXdGQVlJS3dZQkJRVUhBd0VHQ0NzR0FRVUYKQndNQ01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZOOEt0MTJiVXhtcEw2RkN0em9kTlVQWAo2SlIrTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFDYTV4eEI0UnFWUVkxaCtvbEtCMG5BRHhONDd6bjhVY3BIClNzdkdvYjZaYmtjOHY5M0ZUcjhXNit5Tk9GSGQ4Wk5za2JMenVJblZmS0pRUjJSVHZMTVdCajlOUllHd1ZKRHIKYVprbE8yL2k4NkhBa2wyT1hKUlJzTEhNWTA2VTdxenBJTWhDWHpKdk5WekdoNFhGd3k0T2g5Q2J4dTNMTWN3Vwp0Wk5lVXIyZEpYUEF5TVFrVmVYTzd1WkFJNFpCbnNxQ3N0RlNnNEUvWGlDbEFUemNpbW1hSjhLK0Y4TUc0ay9aCjcxZVJQS25XRytnUHdhZ1ZSRnlBc2NmM3E4V1dvOHIzRENlM20rcjZiSGlhY0JFZVFlNnUrRWZoQjROZ3kvUXcKQ1VQTzIzUU1rc3gvY0dJS3U4U1VDU2VXbGJGWjYycVpYeWlXWERIRDB5TTNOdjl1NXQ2YgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    service:
      name: kong-ingress-controller-validation-webhook
      namespace: kong
