gateway:
  admin:
    http:
      enabled: true
  proxy:
    type: NodePort
    http:
      enabled: true
      nodePort: 32001
    tls:
      enabled: true
      nodePort: 32002
controller:
  ingressController:
    env:
      gateway_api_controller_name: konghq.com/kic-gateway-controller-http
