apiVersion: gateway.networking.k8s.io/v1alpha2
kind: UDPRoute
metadata:
 name: udp-route-ifra
 namespace: infra
spec:
 parentRefs:
 - name: kong-gateway-common-teams-nonhttp
   sectionName: stream9002
   namespace: private-gateway-nonhttp
 rules:
 - backendRefs:
   - name: tftp
     port: 9999
     kind: Service
     namespace: devops